//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonusarakOgrenProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorularr
    {
        public int soruId { get; set; }
        public Nullable<int> sınavId { get; set; }
        public string soru1 { get; set; }
        public string soru2 { get; set; }
        public string soru3 { get; set; }
        public string soru4 { get; set; }
        public string cvpA { get; set; }
        public string cvpB { get; set; }
        public string cvpC { get; set; }
        public string cvpD { get; set; }
        public string DogruCvp { get; set; }
    
        public virtual Sınavlar Sınavlar { get; set; }
    }
}
