<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SınavListeEkranı.aspx.cs" Inherits="KonusarakOgrenProje.SınavListeEkranı" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
       <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" DataSourceID="SqlDataSource2" DataKeyNames="sınavId" AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" GridLines="None" Height="224px" Width="542px" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:BoundField DataField="sınavId" HeaderText="sınavId" ReadOnly="True" SortExpression="sınavId" />
                <asp:BoundField DataField="baslik" HeaderText="baslik" SortExpression="baslik" />
                <asp:BoundField DataField="tarih" HeaderText="tarih" SortExpression="tarih" />
                <asp:ButtonField ButtonType="Button" CommandName="Select" Text="Seciniz" />
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:KonusarakOgrenProjeDBConnectionString %>" SelectCommand="SELECT * FROM [Sınavlar]" DeleteCommand="DELETE from [Sınavlar] where [sınavId]=@sınavId"></asp:SqlDataSource>
    </div>
    </form>
</body>
</html>
